### PR TITLE
0.2 Preview Release Prep

### PR DESCRIPTION
**Pull request by rtbenfield**
This PR bumps the package version to 0.2 in preparation for the release. Dependencies were also updated to the latest versions available and @rythos42 was added as a contributor in the package.json.

### CODE REVIEW

**Comment by rtbenfield** [comment]
Attaching VSIX installer for manual testing. @rythos42 I went through a few of my example projects I normally test with. If you get some time can you try it out as well?

[vscode-jest-test-adapter.zip](https://github.com/rtbenfield/vscode-jest-test-adapter/files/2923389/vscode-jest-test-adapter.zip)

**Comment by rythos42** [comment]
@rtbenfield I approved the PR but GitHub says "Review required" still? Thoughts?

**Comment by rythos42** [comment]
I don't think I have "write" access? I tried to create a branch in the repo and push it but it told me I was forbidden (403). GitHub requires that approvers have write access in order to approve PRs.

**Comment by rtbenfield** [comment]
@rythos42  I have not had anywhere near the time I had hoped to lately, but I finally got back to this and added you as a collaborator. You should be able to approve PRs now and push new branches up without having to use your fork.

**Comment by rythos42** [comment]
I hear you! After my last commit I got crazy busy. But the nice thing is that I've had a lot of time to use this extension and I'm really happy with where it's at! It's like 80% usable for my daily use (snapshots are still a notable issue).

**Pull request merged**
