### PR TITLE
TS test files not being found

### PR DESCRIPTION
**Pull request by rossknudsen**
Relates to #44

I have fixed some issues related to the discovery of tests, in particular TS tests.  The highlights are that the extension debugging experience should be working better and that the Jest config is now loaded correctly from the actual workspace and doesn't just rely on the defaults.

### CODE REVIEW

**Comment by rossknudsen** [comment]
@rtbenfield any chance you could review this PR?  I opened it a while ago with WIP tag in title, but I think it is actually good to merge.

I have some more work to do on it, but that can wait for another PR.

**Comment by hc-danieltiziani** [comment]
Any news on this? My project also does not show any tests. It's basically apis with Typescript.

**Comment by rossknudsen** [comment]
@hc-danieltiziani it appears like this project is abandoned.  So I started a new project [here](https://github.com/kavod-io/vscode-jest-test-adapter).  I needed something to practice my DevOps skills on.  It is almost ready for a new pre-release, but not quite.

**Comment by hc-danieltiziani** [comment]
> @hc-danieltiziani it appears like this project is abandoned. So I started a new project [here](https://github.com/kavod-io/vscode-jest-test-adapter). I needed something to practice my DevOps skills on. It is almost ready for a new pre-release, but not quite.

Thanks @rossknudsen , I'll take a look. I don't have time to help with codes this couple of months but maybe I can join in if needed after that. I can help reporting bugs if that helps as well, at least creating repos to reproduce problems.  :-)

**Comment by rythos42** [comment]
I'm not really into this project anymore, but if you're doing a fork and want any of the PR(s?) I made a number of months ago, I'd be good with posting them to your fork.

**Comment by rossknudsen** [comment]
@rythos42 BTH I have changed the code quite a bit, so they probably won't merge anymore. But I should look at the improvements that they made and see what I can translate.

**Comment by rossknudsen** [comment]
@hc-danieltiziani no worries. Testing and bug reports are welcome. 

I'm working on file system watching at the moment which is probably the last feature before the next release.

**Pull request closed without merging**
